name: CI MLflow
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
env:
  # Sesuaikan path jika file csv berada di root atau folder tertentu
  CSV_URL: "wine-quality.csv" 
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # MLflow butuh pandas dan sklearn untuk menjalankan train.py Anda
          pip install mlflow pandas scikit-learn
      
      - name: Run mlflow project
        run: |
          # Menggunakan "." karena MLproject ada di root direktori
          # --env-manager=local memastikan mlflow menggunakan library yang baru diinstall di atas
          mlflow run . --env-manager=local
